### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Exohayvan** [MatthewYork/MiningPoolHub-Swift#1]
iOS 11
iPhone 7

On the Profit Statistics page when you select coin and scroll down the app will force close.

**Comment by MatthewYork** [comment]
Will look into this today

**Comment by MatthewYork** [comment]
Ok, I can replicate it. Will fix soon!

**Comment by MatthewYork** [comment]
This was fixed in commit: 2a7e799f7ea64caffd174cbb76799881cafd476a in the MiningPoolHub-iOS repo. This was a bug in the iOS app, not the underlying swift library.

Fix will be live in version 1.0.2 within a few days!
